interfaces:
  testleaf1:
    loopback: "13.13.13.13"
    int_unnumbered: ["swp1", "swp2", "swp3", "swp4", "swp5", "swp6", "swp7", "swp8"]
    bridges:
      - name: "br0"
        ip_and_mask: "10.4.1.1/25"
        members: ["swp14"]
      - name: "br1"
        ip_and_mask: "10.4.1.129/25"
        members: ["swp15"]
  testeaf2:
    loopback: "14.14.14.14"
    int_unnumbered: ["swp1", "swp2", "swp3", "swp4", "swp5", "swp6", "swp7", "swp8"]
    bridges:
      - name: "br0"
        ip_and_mask: "10.4.2.1/25"
        members: ["swp14"]
      - name: "br1"
        ip_and_mask: "10.4.2.129/25"
        members: ["swp15"]

hostnetranges:
  - 10.4.0.0/16

